[package]
name = "disjoint-hash-set"
version = "0.1.0"
authors = ["snobee <salexwattson@gmail.com>"]
description = "A disjoint set backed by a hash map"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
